### ISSUE TITLE
[ui] Home뷰 구현

### ISSUE THREAD

**Issue by yeonjeen** [DO-SOPT-33rd-CDS-1/LongBlack_Android#11]
## ❗ 이슈 요약
Home 전체 뷰 구현

## 📝 todo

- [x] head뷰 
- [x] note뷰 
- [x] 시간 구현
- [x] go to note 버튼
- [x] go to library 버튼
- [x] 공개 예정 노트 뷰 
- [x] 공개 예정 노트 가롤 스크롤
- [x] 이벤트 뷰 
- [x] 이벤트 슬라이드 
- [x] bottom 삽입
