### ISSUE TITLE
[refactor] Home 뷰 수정

### ISSUE THREAD

**Issue by yeonjeen** [DO-SOPT-33rd-CDS-1/LongBlack_Android#25]
## ❗ 이슈 요약
코드리뷰를 기반으로 수정 사항들 리팩토링

## 📝 todo

- [x] 함수화하기
- [x] LocalData에 있는 함수 사용하기
- [x] String 리소스 사용하기
- [x] 바텀 개별로 넣기
- [x] 시,분,초 텍스트 속성 변경
